# Generated by Django 5.0.6 on 2024-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("share", "0010_alter_dailyprice_date_alter_dailyprice_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                ("portfo", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("price", models.IntegerField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                (
                    "dollar_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dollar_transactions",
                        to="share.dailyprice",
                    ),
                ),
                (
                    "gold_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gold_transactions",
                        to="share.dailyprice",
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ids2transactions",
                        to="share.share",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
