# Generated by Django 5.0.6 on 2024-05-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0011_alter_dailyprice_id"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="dollar_price",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gold_price",
        ),
        migrations.AddField(
            model_name="transaction",
            name="daily_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="share.dailyprice",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
