# Generated by Django 4.2.11 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_transaction_type_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="dollar_gain",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gold_gain",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="dollar_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gold_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
