# Generated by Django 4.2.11 on 2024-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_transaction_dollar_gain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="dollar_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gold_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
