# Generated by Django 4.2.11 on 2024-04-10 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0007_alter_share_share_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellShare',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('portfo', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dollar_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('dollar_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ids2sells', to='share.share')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symbols4sells', to='share.share')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
