# Generated by Django 4.2.11 on 2024-04-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellshare',
            name='share_id',
        ),
    ]
