# Generated by Django 4.2.11 on 2024-04-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_alter_share_share_id'),
        ('sell_share', '0002_remove_sellshare_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellshare',
            name='share_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ids2sells', to='share.share'),
            preserve_default=False,
        ),
    ]
