# Generated by Django 4.2.11 on 2024-04-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_share', '0007_alter_sellshare_dollar_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellshare',
            name='symbol',
        ),
    ]
