# Generated by Django 4.2.11 on 2024-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_share', '0008_remove_sellshare_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellshare',
            old_name='share_id',
            new_name='share',
        ),
        migrations.RenameField(
            model_name='sellshare',
            old_name='user_id',
            new_name='user',
        ),
    ]
