# Generated by Django 5.0.6 on 2024-06-15 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "share_id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SharePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("adj_close", models.FloatField()),
                ("value", models.BigIntegerField()),
                ("volume", models.BigIntegerField()),
                ("count", models.IntegerField()),
                ("yesterday", models.FloatField()),
                ("close", models.FloatField()),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shares2prices",
                        to="share.share",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gold_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dollar_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
