# Generated by Django 4.2.11 on 2024-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
