# Generated by Django 3.2.25 on 2024-06-15 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareprice',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 18, 21, 57, 37067)),
            preserve_default=False,
        ),
    ]
