# Generated by Django 3.2.25 on 2024-06-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_shareprice_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='group',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
