# Generated by Django 3.2.25 on 2024-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20240616_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='group',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='share',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
