# Generated by Django 4.2.11 on 2024-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_alter_share_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
