# Generated by Django 3.2.25 on 2024-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20240616_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareprice',
            name='max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareprice',
            name='min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
