# Generated by Django 3.2.25 on 2024-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20240616_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareprice',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='shareprice',
            name='max',
        ),
        migrations.RemoveField(
            model_name='shareprice',
            name='min',
        ),
    ]
