# Generated by Django 4.2.11 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0007_alter_share_share_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, unique=True)),
                ("gold_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dollar_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
