# Generated by Django 3.2.25 on 2024-06-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20240616_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share2minmax', to='share.share')),
            ],
        ),
    ]
