# Generated by Django 4.2.11 on 2024-05-25 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("share", "0008_dailyprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprice",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_prices",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyprice",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="dailyprice",
            unique_together={("user", "date")},
        ),
    ]
