# Generated by Django 5.0.6 on 2024-05-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0010_alter_dailyprice_date_alter_dailyprice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
